### ISSUE TITLE
Add "return" button that re-syncs the map with the narrative 

### ISSUE THREAD

**Issue by davidmcclure** [sul-cidr/graves#113]
At any point, the reader can leave the pre-defined path through the map defined by the narrative -- pan to other locations, change layers, set filters, etc. When one of these changes is made, a "return" button should be displayed that re-syncs the map with the state defined by the current position in the narrative.

**Comment by snydman** [comment]
"Reset map" to restore initial focus to default opening state of the map (not the narrative)

**Comment by aeschylus** [comment]
- [ ] write leaflet control component for custom button
- [ ] create action to restore original layer states
- [ ] pass behaviour prop down to trigger actions

**Comment by csbailey5t** [comment]
Fixed in #134. In line with our conversation, we returned the map to default state.
