### ISSUE TITLE
Make it possible to download raw data

### ISSUE THREAD

**Issue by davidmcclure** [sul-cidr/graves#115]
Since the town / province data is proprietary, this should just be the `Collection` and `Notice` models. Probably easiest just to provide GeoJSON / CSV download links at the bottom of the landing page.

**Comment by snydman** [comment]
place download control / links on initial splash page.

**Comment by davidmcclure** [comment]
Hi folks, sorry about those phantom `in progress` tags -- those were getting automatically added by [Waffle](https://waffle.io/). Just flipped off the hook for that.
