### ISSUE TITLE
Make it possible to generate "bookmark" urls that capture map / narrative state

### ISSUE THREAD

**Issue by davidmcclure** [sul-cidr/graves#116]
At any point, the reader should be able to generate a durable URL that points back to the current position / state of the narrative:

- Map focus / zoom.
- Demographic layer.
- WMS overlays.
- Timeline range.
- Reading scroll offset (?)

**Comment by snydman** [comment]
hash at end of URL for 

- lat;long;zoom 
- map layers
- narrative state

**Comment by aeschylus** [comment]
We can put the button beneath the reset button as part of that "leaflet panel":

![screen shot 2017-02-01 at 17 08 05](https://cloud.githubusercontent.com/assets/145874/22533166/0c6d9a7e-e8a1-11e6-9318-943f916223e9.png)

The share icon is usually: http://fontawesome.io/icon/share-alt/

**Comment by mejackreed** [comment]
Curious, why > Leave URL clean until user asks for bookmark.

Could the state always be routable?

**Comment by csbailey5t** [comment]
If we're passing 7 different parameters through the URL, we're likely to end up with somewhat ugly URLS. I think the general idea was to keep them nice and clean until necessary. We just have to figure out how to do that.

**Comment by aeschylus** [comment]
There's also an implementation concern. We want to avoid implementing fully-fledged routing unless truly necessary, especially since the map widget is hosted in a page with other state of its own.

Last we talked about this I thought we had settled on using query params or a hash instead of routing.
