### ISSUE TITLE
Improve interaction for overlapping nodes

### ISSUE THREAD

**Issue by snydman** [sul-cidr/graves#121]
@mejackreed does Leaflet have ways of dealing with this? 

![image](https://cloud.githubusercontent.com/assets/3279382/22443485/dde0ffe2-e6f3-11e6-9baf-c5918e88275b.png)

**Comment by mejackreed** [comment]
I'm not sure what the issue is? Could you explain the problem a bit more?

**Comment by csbailey5t** [comment]
@mejackreed Right now there are significant clusters of overlapping nodes, making it hard to select individual records. It would enhance the UI to be able to expand the clusters to make them interactively distinct.

**Comment by aeschylus** [comment]
@ggeisler and I were talking about this one with Stu this afternoon and came up with a solution that should address most of the drawbacks of the current implementation without being too involved.

Leaflet [markerclusters](http://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html) came up, but we noted a few drawbacks. First was the impression that its behaviour is a bit inconsistent: sometimes the markers animate in and out of their clusters and sometimes they don't. We also thought there might be significant rework on the time slider to support the filtering behaviour in a way that works with the clustering presentation. Currently this is accomplished by a simple d3 selection on the existing DOM, which would not work with the markercluster plugin.

After some more spitballing, we came up with the proposal of a "click to zoom" link/button placed inside the existing collection modal. When the user clicks on any circle, the collection modal comes up as it is, but would have another section of content with "nearby" nodes and the zoom-in link. The zoom-in link would zoom down to the maximum (or some safe high number) zoom level centred on the currently selected marker. They could then pan around from there to see disambiguated incidents, where it is easier to distinguish their previously overlapping markers.
