### ISSUE TITLE
Rectangular region frames seem clickable, but aren't.

### ISSUE THREAD

**Issue by aeschylus** [sul-cidr/graves#135]
The frames regions with section titles attaches to them have a "pointer" mouse effect when hovering over the title. This implies that the user can click them. I would suggest we either remove the pointer effect or implement the implied behaviour. 

I expected it to zoom into the framed region and scroll to the appropriate section of the essay to the left.

**Comment by csbailey5t** [comment]
It makes sense to me to simply remove the "pointer" effect and switch it to "grab" as in other parts of the map. This way we allow the narrative to continue to drive the map navigation in terms of defined sections/chunks.
