### ISSUE TITLE
Figure out how compiled assets are supposed to be deployed

### ISSUE THREAD

**Issue by mejackreed** [sul-cidr/graves#149]
How are we supposed to deploy the grunted site.css and site.js?

**Comment by mejackreed** [comment]
`public/javascripts/*js`
`public/stylesheeets/*.css`

need to be synced up 

`rsync -av public/stylesheets/*.css cidr@cidr-graves-stage.stanford.edu:/opt/app/cidr/graves/current/public/stylesheets/`

**Comment by davidmcclure** [comment]
I'm fuzzy on this, but I believe before the asset compile was happening on the server? I think there was a npm postinstall hook that ran `grunt compile:min`.

`rsync`ing up local files would work, though one caveat is that the person doing the deploy would have to make sure that they have minified files built locally, not compressed. By default, the grunt watch in development doesn't minify, to make the compile loop faster.

**Comment by mejackreed** [comment]
👍 thanks for that @davidmcclure exactly what I needed
